# Generated by Django 3.0.6 on 2020-05-29 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='tweet_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
