# Generated by Django 3.0.6 on 2020-05-29 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200529_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='following',
        ),
        migrations.AddField(
            model_name='account',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
